(function(){
  "use strict";
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const db=window.JMP_DB;
  const ROUTES={dashboard:["Tableau de bord","Référentiel RF / CPMA et activité professionnelle"],journal:["Journal des services","Saisie et historique des services effectués"],rf:["RF / CPMA","Synthèse mensuelle, données quotidiennes et contrôles"],imports:["Imports et contrôle","Classeur de reconstitution et bulletins PDF"],incidents:["Incidents","Registre factuel des événements professionnels"],dsp:["Dossier DSP","Paramètres et éléments de suivi du lot 49"],exports:["Exports et sauvegarde","Excel, PDF, CSV et sauvegarde locale"],settings:["Paramètres","Règles de calcul, maintenance et confidentialité"]};
  const LINES=["20","26","29","32","38","39","40","46","48","56","57","60","69","76","77","80","86","87","96","98","102","109","115","121","122","129","202","215","245","318","322","341","Roissybus","N01","N02","N13","N15","N41","N42","N43","N44","N45","N51","N52","N53","N551"];
  const state={months:[],days:[],services:[],documents:[],incidents:[],dsp:null,rules:null,pendingImport:null,currentRoute:"dashboard",currentMonth:null,currentDocument:null,deferredInstall:null};

  const html=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const num=v=>Number.isFinite(Number(v))?Number(v):0;
  const round=(v,n=3)=>Math.round((num(v)+Number.EPSILON)*10**n)/10**n;
  const rf=v=>{const n=round(v,3);return n.toLocaleString("fr-FR",{minimumFractionDigits:3,maximumFractionDigits:3});};
  const signedRF=v=>`${num(v)>0?"+":""}${rf(v)}`;
  const dateFR=iso=>{if(!iso)return"—";const d=new Date(`${iso}T12:00:00`);return Number.isNaN(d.getTime())?iso:d.toLocaleDateString("fr-FR");};
  const periodFR=p=>{if(!p)return"—";const [y,m]=p.split("-");return new Date(Number(y),Number(m)-1,1).toLocaleDateString("fr-FR",{month:"long",year:"numeric"});};
  const hours=minutes=>{if(minutes==null)return"—";const sign=minutes<0?"−":"";let m=Math.abs(Math.round(minutes));return`${sign}${Math.floor(m/60)} h ${String(m%60).padStart(2,"0")}`;};
  const uid=prefix=>`${prefix}-${crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random().toString(16).slice(2)}`;
  const classNum=v=>num(v)<-0.0005?"negative":num(v)>0.0005?"positive-text":"";
  function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("show"),2600);}
  function downloadBlob(name,blob){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),3000);}
  function downloadText(name,text,type="text/plain;charset=utf-8"){downloadBlob(name,new Blob([text],{type}));}
  function localToday(){const d=new Date(),off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,10);}
  function hhmm(v){const s=String(v||"").replace(/\D/g,"").slice(0,4);return s.length===3?"0"+s:s;}
  function minuteOfDay(v){v=hhmm(v);if(!/^\d{4}$/.test(v))return null;const h=+v.slice(0,2),m=+v.slice(2);return h<24&&m<60?h*60+m:null;}
  function duration(start,end){const a=minuteOfDay(start),b=minuteOfDay(end);if(a==null||b==null)return 0;return b>=a?b-a:b+1440-a;}

  async function loadState(){
    [state.months,state.days,state.services,state.documents,state.incidents]=await Promise.all([db.getAll("months"),db.getAll("days"),db.getAll("services"),db.getAll("documents"),db.getAll("incidents")]);
    state.dsp=await db.get("dsp","main")||{id:"main"};
    state.rules=(await db.get("settings","rules"))?.value||{worked:.252,sunday:1.252,taken:-1,pointZero:.19};
    state.months.sort((a,b)=>a.period.localeCompare(b.period));state.days.sort((a,b)=>a.date.localeCompare(b.date));state.services.sort((a,b)=>(b.date||"").localeCompare(a.date||""));state.incidents.sort((a,b)=>(b.date||"").localeCompare(a.date||""));
  }

  async function init(){
    try{
      await db.initialize(window.JMP_SEED);
      await loadState();
      bindEvents();populateStatic();renderAll();const initial=location.hash.slice(1);route(ROUTES[initial]?initial:"dashboard");
      $("#dbStatus").textContent="Base locale opérationnelle";$("#loading").classList.add("hidden");
      if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js").catch(console.warn);
    }catch(e){console.error(e);$("#loading").innerHTML=`<strong>Impossible d’initialiser l’application.</strong><p>${html(e.message)}</p>`;$("#dbStatus").textContent="Erreur locale";}
  }

  function populateStatic(){
    $("#lineList").innerHTML=LINES.map(x=>`<option value="${html(x)}"></option>`).join("");
    const years=[...new Set(state.months.map(m=>m.year))];$("#rfYearFilter").innerHTML='<option value="">Toutes les années</option>'+years.map(y=>`<option>${y}</option>`).join("");
    if(!$("#serviceDate").value)$("#serviceDate").value=localToday();if(!$("#incidentDate").value)$("#incidentDate").value=localToday();
    renderRulesForm();renderDSPForm();
  }

  function route(name){
    if(name==="more"){$(".sidebar").classList.toggle("open");return;}
    if(!ROUTES[name])name="dashboard";state.currentRoute=name;history.replaceState(null,"","#"+name);
    $$(".view").forEach(v=>v.classList.toggle("active",v.dataset.view===name));
    $$("[data-route]").forEach(b=>b.classList.toggle("active",b.dataset.route===name));
    $("#pageTitle").textContent=ROUTES[name][0];$("#pageSubtitle").textContent=ROUTES[name][1];$(".sidebar").classList.remove("open");window.scrollTo({top:0,behavior:"instant"});
    if(name==="dashboard")renderDashboard();if(name==="journal")renderServices();if(name==="rf")renderRF();if(name==="imports")renderDocuments();if(name==="incidents")renderIncidents();if(name==="dsp")renderDSP();
  }

  function renderAll(){renderDashboard();renderServices();renderRF();renderDocuments();renderIncidents();renderDSP();renderRulesForm();}

  function renderDashboard(){
    if(!state.months.length)return;
    const latest=state.months.at(-1),docsCovered=new Set(state.documents.filter(d=>d.period).map(d=>d.period)).size;
    $("#kpiGrid").innerHTML=[
      ["RF théorique",rf(latest.personalCumulative),"Cumul personnel hors écritures CPMA","positive"],
      ["RF bulletin",rf(latest.officialClosing),`Solde officiel au ${latest.period}`,""],
      ["Différentiel",signedRF(latest.cumulativeGap),"Écart cumulé à documenter","alert"],
      ["Périodes documentées",`${docsCovered} / ${state.months.length}`,`${state.documents.length} PDF conservé${state.documents.length>1?"s":""}`,""]
    ].map(([l,v,d,c])=>`<article class="kpi ${c}"><div class="label">${l}</div><div class="value">${v}</div><div class="detail">${d}</div></article>`).join("");
    $("#rfChart").innerHTML=lineChart(state.months);
    const controlErrors=state.months.filter(m=>Math.abs(num(m.control))>.0005),review=state.documents.filter(d=>d.status==="review").length;
    $("#controlList").innerHTML=`
      <div class="stack-item ${controlErrors.length?"warn":"ok"}"><strong>${controlErrors.length?`${controlErrors.length} contrôle(s) à vérifier`:"Contrôles mensuels cohérents"}</strong><small>Ouverture + mouvement + CPMA = clôture officielle.</small></div>
      <div class="stack-item ${docsCovered===state.months.length?"ok":"warn"}"><strong>${docsCovered} période(s) avec PDF lié</strong><small>${state.months.length-docsCovered} période(s) restent sans pièce importée dans l’application.</small></div>
      <div class="stack-item ${review?"warn":"ok"}"><strong>${review?`${review} PDF à contrôler`:"Aucun PDF en attente"}</strong><small>L’extraction automatique reste soumise à validation humaine.</small></div>
      <div class="stack-item ok"><strong>−12 RF neutralisés en février 2024</strong><small>Transfert identifié vers le CET, isolé du différentiel.</small></div>`;
    $("#recentServices").innerHTML=state.services.length?state.services.slice(0,4).map(s=>`<div class="stack-item"><strong>${dateFR(s.date)} · L${html(s.line)} / S${html(s.service)}</strong><small>${html(s.uo||"")} · ${html(s.start||"—")}–${html(s.end||"—")} ${s.note?"· "+html(s.note.slice(0,80)):""}</small></div>`).join(""):'<div class="empty">Aucun service enregistré.</div>';
    $("#latestMonthLabel").textContent=periodFR(latest.period);
    $("#latestMonthCard").innerHTML=`<div class="metric-pair"><span>Ouverture officielle</span><strong>${rf(latest.officialOpening)}</strong></div><div class="metric-pair"><span>Mouvement RF</span><strong class="${classNum(latest.movementRF)}">${signedRF(latest.movementRF)}</strong></div><div class="metric-pair"><span>CPMA</span><strong class="${classNum(latest.cpma)}">${signedRF(latest.cpma)}</strong></div><div class="metric-pair"><span>Clôture officielle</span><strong>${rf(latest.officialClosing)}</strong></div><div class="metric-pair"><span>Écart cumulé</span><strong class="negative">${signedRF(latest.cumulativeGap)}</strong></div>`;
  }

  function lineChart(months){
    const W=900,H=300,p={l:48,r:18,t:20,b:40};const vals=months.flatMap(m=>[num(m.officialClosing),num(m.personalCumulative)]);let min=Math.min(0,...vals),max=Math.max(...vals);max=Math.ceil(max/10)*10;const x=i=>p.l+i*(W-p.l-p.r)/(months.length-1),y=v=>p.t+(max-v)*(H-p.t-p.b)/(max-min||1);
    const points=key=>months.map((m,i)=>`${x(i).toFixed(1)},${y(m[key]).toFixed(1)}`).join(" ");const grid=[];for(let i=0;i<=5;i++){const v=min+(max-min)*i/5,yy=y(v);grid.push(`<line class="chart-grid" x1="${p.l}" y1="${yy}" x2="${W-p.r}" y2="${yy}"/><text class="chart-axis" x="${p.l-8}" y="${yy+4}" text-anchor="end">${Math.round(v)}</text>`);}const labels=months.map((m,i)=>i%6===0||i===months.length-1?`<text class="chart-axis" x="${x(i)}" y="${H-12}" text-anchor="middle">${m.period}</text>`:"").join("");const area=`${p.l},${y(0)} ${points("personalCumulative")} ${W-p.r},${y(0)}`;
    return`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Évolution RF officiel et théorique">${grid.join("")}<polygon class="chart-area" points="${area}"/><polyline class="chart-official" points="${points("officialClosing")}"/><polyline class="chart-personal" points="${points("personalCumulative")}"/>${labels}</svg>`;
  }

  function serviceFromForm(){
    const original=$("#serviceId").value;const record={id:original||uid("service"),date:$("#serviceDate").value,uo:$("#serviceUo").value,line:$("#serviceLine").value.trim().toUpperCase(),service:$("#serviceNumber").value.trim(),police:$("#servicePolice").value.trim(),vehicle:$("#serviceVehicle").value.trim(),start:hhmm($("#serviceStart").value),end:hhmm($("#serviceEnd").value),split:$("#serviceSplit").checked,start2:hhmm($("#serviceStart2").value),end2:hhmm($("#serviceEnd2").value),delay:$("#serviceDelay").checked,shift:$("#serviceShift").checked,incident:$("#serviceIncident").checked,accident:$("#serviceAccident").checked,location:$("#serviceLocation").value.trim(),note:$("#serviceNote").value.trim(),updatedAt:new Date().toISOString()};record.durationMinutes=duration(record.start,record.end)+(record.split?duration(record.start2,record.end2):0);record.createdAt=state.services.find(s=>s.id===record.id)?.createdAt||record.updatedAt;return record;
  }
  function updateDuration(){const mins=duration($("#serviceStart").value,$("#serviceEnd").value)+($("#serviceSplit").checked?duration($("#serviceStart2").value,$("#serviceEnd2").value):0);$("#durationPreview").textContent=`Durée calculée : ${mins?hours(mins):"—"}`;}
  function resetServiceForm(){$("#serviceForm").reset();$("#serviceId").value="";$("#serviceDate").value=localToday();$("#serviceUo").value="BELLIARD";$("#serviceFormTitle").textContent="Nouveau service";$("#splitFields").classList.add("hidden");updateDuration();}
  function editService(id){const s=state.services.find(x=>x.id===id);if(!s)return;const map={serviceId:s.id,serviceDate:s.date,serviceUo:s.uo||"BELLIARD",serviceLine:s.line,serviceNumber:s.service,servicePolice:s.police,serviceVehicle:s.vehicle,serviceStart:s.start,serviceEnd:s.end,serviceStart2:s.start2,serviceEnd2:s.end2,serviceLocation:s.location,serviceNote:s.note};Object.entries(map).forEach(([id,v])=>{const e=$("#"+id);if(e)e.value=v||"";});$("#serviceSplit").checked=!!s.split;$("#serviceDelay").checked=!!s.delay;$("#serviceShift").checked=!!s.shift;$("#serviceIncident").checked=!!s.incident;$("#serviceAccident").checked=!!s.accident;$("#splitFields").classList.toggle("hidden",!s.split);$("#serviceFormTitle").textContent="Modifier le service";updateDuration();window.scrollTo({top:0,behavior:"smooth"});}
  function renderServices(){
    const q=$("#serviceSearch")?.value.trim().toLowerCase()||"",month=$("#serviceFilterDate")?.value||"";const rows=state.services.filter(s=>(!month||s.date?.startsWith(month))&&(!q||[s.date,s.uo,s.line,s.service,s.police,s.vehicle,s.location,s.note].join(" ").toLowerCase().includes(q)));
    $("#serviceCount").textContent=`${rows.length} service${rows.length>1?"s":""} affiché${rows.length>1?"s":""} · ${state.services.length} au total`;
    $("#serviceList").innerHTML=rows.length?rows.map(s=>{const flags=[s.delay&&"Retard",s.shift&&"Décalage",s.incident&&"Incident",s.accident&&"Accident",s.split&&"2×"].filter(Boolean);return`<article class="record-card"><div class="record-card-head"><div><div class="record-title">${dateFR(s.date)} — L${html(s.line)} / S${html(s.service)}</div><div class="record-meta">${html(s.uo||"")} · Police ${html(s.police||"—")} · Coquille ${html(s.vehicle||"—")} · ${html(s.start||"—")}–${html(s.end||"—")} ${s.split?`/ ${html(s.start2||"—")}–${html(s.end2||"—")}`:""} · ${hours(s.durationMinutes||0)}</div><div>${flags.map(f=>`<span class="badge ${f==="Incident"||f==="Accident"?"bad":""}">${f}</span>`).join(" ")}</div></div><div class="record-actions"><button class="text-button" data-edit-service="${s.id}">Modifier</button><button class="text-button negative" data-delete-service="${s.id}">Supprimer</button></div></div>${s.location?`<div class="record-meta">Lieu : ${html(s.location)}</div>`:""}${s.note?`<div class="record-note">${html(s.note)}</div>`:""}</article>`;}).join(""):'<div class="empty">Aucun service ne correspond au filtre.</div>';
  }

  async function recalculateMonths({fromDays=false,persist=true}={}){
    const sorted=[...state.months].sort((a,b)=>a.period.localeCompare(b.period));let personal=num(state.rules.pointZero);
    for(const m of sorted){if(fromDays)m.movementRF=round(state.days.filter(d=>d.period===m.period).reduce((a,d)=>a+num(d.rfNet),0),6);m.theoreticalBeforeCPMA=round(num(m.officialOpening)+num(m.movementRF)+num(m.recognizedAdjustment),6);personal=round(personal+num(m.movementRF)+num(m.recognizedAdjustment),6);m.personalCumulative=personal;m.cumulativeGap=round(personal-num(m.officialClosing),6);m.control=round(num(m.officialOpening)+num(m.movementRF)+num(m.cpma)-num(m.officialClosing),9);}
    state.months=sorted;if(persist)await db.replaceStore("months",sorted);
  }

  function filteredMonths(){const year=$("#rfYearFilter")?.value||"",uo=$("#rfUoFilter")?.value||"";return state.months.filter(m=>(!year||String(m.year)===year)&&(!uo||m.uo===uo));}
  function renderRF(){
    const rows=filteredMonths();$("#rfTableBody").innerHTML=rows.map(m=>`<tr><td><strong>${m.period}</strong><br><span class="record-meta">${html(m.monthName)}</span></td><td>${html(m.uo)}</td><td class="number">${rf(m.officialOpening)}</td><td class="number ${classNum(m.movementRF)}">${signedRF(m.movementRF)}</td><td class="number ${classNum(m.recognizedAdjustment)}">${signedRF(m.recognizedAdjustment)}</td><td class="number">${rf(m.theoreticalBeforeCPMA)}</td><td class="number ${classNum(m.cpma)}">${signedRF(m.cpma)}</td><td class="number">${rf(m.officialClosing)}</td><td class="number positive-text">${rf(m.personalCumulative)}</td><td class="number negative">${signedRF(m.cumulativeGap)}</td><td class="number"><span class="badge ${Math.abs(num(m.control))<.0005?"good":"bad"}">${rf(m.control)}</span></td><td><button class="text-button" data-month="${m.period}">Détail</button></td></tr>`).join("");
    renderHoursSummary(rows);renderMethodology();
  }
  function renderHoursSummary(rows){const normal=rows.reduce((a,m)=>a+num(m.normalMinutes),0),rt=rows.reduce((a,m)=>a+num(m.presumedRTMinutes),0),ts=rows.reduce((a,m)=>a+num(m.assimilatedTSMinutes),0),max=Math.max(normal,rt,ts,1);$("#hoursSummary").innerHTML=`<div class="hours-bars">${[["Travail normal",normal,""],["RT présumés",rt,"rt"],["TS assimilés",ts,"ts"]].map(([l,v,c])=>`<div class="bar-row"><span>${l}</span><div class="bar-track"><div class="bar-fill ${c}" style="width:${100*v/max}%"></div></div><strong>${hours(v)}</strong></div>`).join("")}</div><p class="warning-box">La qualification « RT présumé » demeure analytique et doit être rapprochée des règles internes applicables.</p>`;}
  function renderMethodology(){$("#methodologyCard").innerHTML=`<div><strong>Point zéro</strong><span>${rf(state.rules.pointZero)} RF au début de février 2023.</span></div><div><strong>Acquisition</strong><span>${rf(state.rules.worked)} par jour travaillé ; ${rf(state.rules.sunday)} le dimanche travaillé.</span></div><div><strong>RF pris</strong><span>${rf(state.rules.taken)} RF.</span></div><div><strong>CPMA</strong><span>Écriture mensuelle issue de la ligne REPOS FIXE du bulletin.</span></div><div><strong>Février 2024</strong><span>−12 RF isolés comme transfert reconnu vers le CET.</span></div><div><strong>Juin 2025</strong><span>AUBER du 1 au 23 ; BELLIARD du 24 au 30.</span></div>`;}
  function openMonth(period){
    const m=state.months.find(x=>x.period===period);if(!m)return;state.currentMonth=period;$("#monthDialogTitle").textContent=periodFR(period);$("#monthDialogSubtitle").textContent=`${m.uo} · source : ${m.source||"non renseignée"}`;
    const days=state.days.filter(d=>d.period===period);$("#monthDialogBody").innerHTML=`<div class="about-grid"><div><strong>Ouverture officielle</strong><span>${rf(m.officialOpening)}</span></div><div><strong>Mouvement RF</strong><span>${signedRF(m.movementRF)}</span></div><div><strong>CPMA</strong><span>${signedRF(m.cpma)}</span></div><div><strong>Clôture officielle</strong><span>${rf(m.officialClosing)}</span></div></div><h3 style="margin-top:18px">Détail quotidien</h3><div class="daily-grid">${days.map(d=>`<div class="daily-cell ${d.rfTaken?"rf":d.rfAcquisition?"work":""}"><span class="day">${d.day}</span><div>${html(d.plannedCode||"—")}</div><div class="rfv ${classNum(d.rfNet)}">RF ${d.rfNet==null?"—":signedRF(d.rfNet)}</div><div>${d.normalMinutes!=null?hours(d.normalMinutes):""}</div>${d.supplementaryMinutes?`<div>Suppl. ${hours(d.supplementaryMinutes)}</div>`:""}</div>`).join("")}</div><h3 style="margin-top:18px">Écritures mensuelles</h3><div class="form-grid"><label>Ouverture officielle<input id="editOpening" type="number" step="0.001" value="${m.officialOpening}"></label><label>CPMA<input id="editCpma" type="number" step="0.001" value="${m.cpma}"></label><label>Clôture officielle<input id="editClosing" type="number" step="0.001" value="${m.officialClosing}"></label><label>Ajustement reconnu<input id="editAdjustment" type="number" step="0.001" value="${m.recognizedAdjustment}"></label><label class="span-2">Source<input id="editSource" value="${html(m.source||"")}"></label><label class="span-2">Note<textarea id="editMonthNote" rows="3">${html(m.note||"")}</textarea></label></div>`;$("#monthDialog").showModal();
  }
  async function saveMonth(){const m=state.months.find(x=>x.period===state.currentMonth);if(!m)return;m.officialOpening=num($("#editOpening").value);m.cpma=num($("#editCpma").value);m.officialClosing=num($("#editClosing").value);m.recognizedAdjustment=num($("#editAdjustment").value);m.source=$("#editSource").value.trim();m.note=$("#editMonthNote").value.trim();m.updatedAt=new Date().toISOString();await db.put("months",m);await recalculateMonths();await loadState();renderAll();$("#monthDialog").close();toast("Période mise à jour et cumul recalculé.");}

  async function handleXlsx(file){
    $("#xlsxImportStatus").textContent=`Lecture de ${file.name}…`;
    try{const sheets=await JMPXLSX.readWorkbook(await file.arrayBuffer());const parsed=JMPXLSX.parseReconstruction(sheets);const diffs=[];for(const m of parsed.monthly){const old=state.months.find(x=>x.period===m.period);if(!old){diffs.push({period:m.period,type:"nouvelle"});continue;}const fields=["officialOpening","movementRF","recognizedAdjustment","cpma","officialClosing"];const changed=fields.filter(f=>Math.abs(num(old[f])-num(m[f]))>.0005);if(changed.length)diffs.push({period:m.period,type:"modifiée",fields:changed});}state.pendingImport={...parsed,fileName:file.name,diffs};$("#xlsxImportStatus").textContent=`${parsed.summary.months} mois et ${parsed.summary.days} journées détectés.`;renderImportPreview();}catch(e){console.error(e);$("#xlsxImportStatus").textContent=`Erreur : ${e.message}`;toast("Classeur non importé.");}
  }
  function renderImportPreview(){const p=state.pendingImport;if(!p)return;$("#importPreviewPanel").classList.remove("hidden");$("#importPreviewSummary").textContent=`${p.summary.months} mois · ${p.summary.days} journées · ${p.diffs.length} différence(s) par rapport à la base actuelle.`;$("#importPreview").innerHTML=`${p.warnings.length?`<div class="warning-box">${p.warnings.map(html).join("<br>")}</div>`:""}<div class="table-scroll"><table class="data-table"><thead><tr><th>Période</th><th>État</th><th>Champs concernés</th></tr></thead><tbody>${p.diffs.length?p.diffs.map(d=>`<tr><td>${d.period}</td><td><span class="badge ${d.type==="nouvelle"?"good":"warn"}">${d.type}</span></td><td>${html((d.fields||[]).join(", ")||"Nouvelle période")}</td></tr>`).join(""):'<tr><td colspan="3">Aucune différence numérique majeure détectée.</td></tr>'}</tbody></table></div>`;}
  async function confirmImport(){const p=state.pendingImport;if(!p)return;const now=new Date().toISOString();p.monthly.forEach(m=>{m.status="validated";m.origin="import_xlsx_validated";m.note=`Import validé depuis ${p.fileName}.`;m.updatedAt=now;});await db.replaceStore("months",p.monthly);await db.replaceStore("days",p.daily);await db.audit("xlsx_import_validated",{file:p.fileName,months:p.monthly.length,days:p.daily.length,differences:p.diffs.length});state.pendingImport=null;$("#importPreviewPanel").classList.add("hidden");$("#xlsxInput").value="";await loadState();await recalculateMonths();await loadState();renderAll();toast("Classeur validé et base historique remplacée.");}

  function normalizeFilename(s){return String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]/g,"");}
  function matchPeriodFromName(name){const n=normalizeFilename(name);const exact=state.months.find(m=>normalizeFilename(m.source)===n);if(exact)return exact.period;const mm=n.match(/(20\d{2})(0[1-9]|1[0-2])/);return mm?`${mm[1]}-${mm[2]}`:"";}
  async function handlePdfs(files){
    const arr=[...files];let done=0;for(const file of arr){$("#pdfImportStatus").textContent=`Analyse ${done+1}/${arr.length} : ${file.name}`;try{const extraction=await JMPPDF.extract(file);const period=extraction.period||matchPeriodFromName(file.name);const duplicate=state.documents.find(d=>d.name===file.name&&d.size===file.size);const doc={id:duplicate?.id||uid("pdf"),name:file.name,size:file.size,type:file.type||"application/pdf",lastModified:file.lastModified,period,file,extraction,status:period?"matched":"review",importedAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await db.put("documents",doc);done++;}catch(e){console.error(e);const doc={id:uid("pdf"),name:file.name,size:file.size,type:file.type||"application/pdf",lastModified:file.lastModified,period:matchPeriodFromName(file.name),file,status:"review",extraction:{confidence:"nulle",text:"",relevantLines:[],warning:e.message},importedAt:new Date().toISOString()};await db.put("documents",doc);done++;}}
    $("#pdfInput").value="";$("#pdfImportStatus").textContent=`${done} PDF importé${done>1?"s":""} et conservé${done>1?"s":""} localement.`;await loadState();renderDocuments();renderDashboard();toast("Import PDF terminé. Contrôle humain requis.");
  }
  function renderDocuments(){const status=$("#documentStatusFilter")?.value||"",docs=state.documents.filter(d=>!status||d.status===status).sort((a,b)=>(b.importedAt||"").localeCompare(a.importedAt||""));$("#documentCount").textContent=`${docs.length} document${docs.length>1?"s":""} affiché${docs.length>1?"s":""} · ${state.documents.length} au total`;$("#documentTableBody").innerHTML=docs.length?docs.map(d=>`<tr><td>${d.period||'<span class="badge bad">Non identifié</span>'}</td><td><strong>${html(d.name)}</strong><br><span class="record-meta">${Math.round(d.size/1024)} Ko</span></td><td>${d.period?`<span class="badge good">${state.months.some(m=>m.period===d.period)?"Période trouvée":"Période hors base"}</span>`:'<span class="badge bad">À rattacher</span>'}</td><td><span class="badge ${d.extraction?.confidence==="élevée"?"good":d.extraction?.confidence==="moyenne"?"warn":"bad"}">${html(d.extraction?.confidence||"non faite")}</span><br><span class="record-meta">${d.extraction?.charCount||0} caractères</span></td><td><span class="badge ${d.status==="validated"?"good":d.status==="matched"?"warn":"bad"}">${d.status==="validated"?"Validé":d.status==="matched"?"Rapproché":"À vérifier"}</span></td><td><button class="text-button" data-view-document="${d.id}">Contrôler</button><button class="text-button negative" data-delete-document="${d.id}">Supprimer</button></td></tr>`).join(""):'<tr><td colspan="6" class="empty">Aucun PDF importé.</td></tr>';}
  function openDocument(id){const d=state.documents.find(x=>x.id===id);if(!d)return;state.currentDocument=id;const m=state.months.find(x=>x.period===d.period);$("#documentDialogTitle").textContent=d.name;$("#documentDialogSubtitle").textContent=`${d.period?periodFR(d.period):"Période non identifiée"} · extraction ${d.extraction?.confidence||"non disponible"}`;const objectUrl=d.file instanceof Blob?URL.createObjectURL(d.file):"";$("#documentDialogBody").innerHTML=`<div class="dashboard-grid"><div><h3>Rapprochement</h3>${m?`<div class="metric-pair"><span>Ouverture officielle attendue</span><strong>${rf(m.officialOpening)}</strong></div><div class="metric-pair"><span>CPMA attendu</span><strong>${signedRF(m.cpma)}</strong></div><div class="metric-pair"><span>Clôture officielle attendue</span><strong>${rf(m.officialClosing)}</strong></div><div class="metric-pair"><span>Source attendue</span><strong style="font-size:.8rem">${html(m.source)}</strong></div>`:'<p class="warning-box">Le fichier n’a pas été rattaché à une période du référentiel.</p>'}<label style="display:grid;gap:5px;margin-top:12px">Période<select id="documentPeriod"><option value="">— Non identifiée —</option>${state.months.map(x=>`<option value="${x.period}" ${x.period===d.period?"selected":""}>${x.period} · ${html(x.monthName)}</option>`).join("")}</select></label>${objectUrl?`<p><a class="button secondary" href="${objectUrl}" target="_blank" rel="noopener">Ouvrir le PDF</a></p>`:""}</div><div><h3>Lignes repérées</h3><div class="raw-text">${html((d.extraction?.relevantLines||[]).join("\n")||d.extraction?.warning||"Aucun texte pertinent extrait.")}</div></div></div><h3>Texte extrait</h3><div class="raw-text">${html(d.extraction?.text||"Aucune couche texte exploitable. Le document reste conservé comme pièce source.")}</div>`;$("#documentDialog").showModal();}
  async function validateDocument(){const d=state.documents.find(x=>x.id===state.currentDocument);if(!d)return;d.period=$("#documentPeriod")?.value||d.period;d.status="validated";d.validatedAt=new Date().toISOString();await db.put("documents",d);$("#documentDialog").close();await loadState();renderDocuments();renderDashboard();toast("Bulletin marqué comme contrôlé.");}

  function resetIncidentForm(){$("#incidentForm").reset();$("#incidentId").value="";$("#incidentDate").value=localToday();$("#incidentFormTitle").textContent="Nouvel événement";}
  function incidentFromForm(){const id=$("#incidentId").value||uid("incident"),old=state.incidents.find(i=>i.id===id);return{id,date:$("#incidentDate").value,type:$("#incidentType").value,line:$("#incidentLine").value.trim().toUpperCase(),service:$("#incidentService").value.trim(),location:$("#incidentLocation").value.trim(),description:$("#incidentDescription").value.trim(),actions:$("#incidentActions").value.trim(),status:$("#incidentStatus").value,reference:$("#incidentReference").value.trim(),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};}
  function editIncident(id){const i=state.incidents.find(x=>x.id===id);if(!i)return;const map={incidentId:i.id,incidentDate:i.date,incidentType:i.type,incidentLine:i.line,incidentService:i.service,incidentLocation:i.location,incidentDescription:i.description,incidentActions:i.actions,incidentStatus:i.status,incidentReference:i.reference};Object.entries(map).forEach(([k,v])=>$("#"+k).value=v||"");$("#incidentFormTitle").textContent="Modifier l’événement";window.scrollTo({top:0,behavior:"smooth"});}
  function renderIncidents(){$("#incidentCount").textContent=`${state.incidents.length} événement${state.incidents.length>1?"s":""}`;$("#incidentList").innerHTML=state.incidents.length?state.incidents.map(i=>`<article class="record-card"><div class="record-card-head"><div><div class="record-title">${dateFR(i.date)} — ${html(i.type)}</div><div class="record-meta">Ligne ${html(i.line||"—")} · Service ${html(i.service||"—")} · ${html(i.location)}</div><span class="badge ${i.status==="Clos"?"good":i.status==="Transmis"?"warn":"bad"}">${html(i.status)}</span></div><div class="record-actions"><button class="text-button" data-edit-incident="${i.id}">Modifier</button><button class="text-button negative" data-delete-incident="${i.id}">Supprimer</button></div></div><div class="record-note"><strong>Faits</strong><br>${html(i.description)}</div>${i.actions?`<div class="record-note"><strong>Mesures prises</strong><br>${html(i.actions)}</div>`:""}</article>`).join(""):'<div class="empty">Aucun incident enregistré.</div>';}

  function renderDSPForm(){const d=state.dsp||{};$("#dspLot").value=d.lot||"49";$("#dspOperator").value=d.operator||"RATP Cap";$("#dspCentres").value=Array.isArray(d.centres)?d.centres.join(", "):d.centres||"Belliard, Les Lilas, Lagny";$("#dspStart").value=d.referencePeriodStart||"2025-10-31";$("#dspEnd").value=d.referencePeriodEnd||"2026-10-31";$("#dspPlannedDays").value=d.plannedDaysPerYear??215;$("#dspExecutedDays").value=d.executedDays??245;$("#dspNote").value=d.note||"";}
  function renderDSP(){const d=state.dsp||{},planned=num(d.plannedDaysPerYear),executed=num(d.executedDays),extra=executed-planned;$("#dspSummary").innerHTML=`<div class="metric-pair"><span>Période de référence</span><strong style="font-size:.92rem">${dateFR(d.referencePeriodStart)} → ${dateFR(d.referencePeriodEnd)}</strong></div><div class="metric-pair"><span>Jours planifiés</span><strong>${planned}</strong></div><div class="metric-pair"><span>Jours exécutés</span><strong>${executed}</strong></div><div class="metric-pair"><span>Écart de charge</span><strong class="${extra>0?"negative":""}">${extra>0?"+":""}${extra} jours</strong></div><p class="warning-box">Cet indicateur décrit la charge enregistrée. Il ne détermine pas, à lui seul, la portée juridique d’une garantie de rémunération.</p>`;}

  function renderRulesForm(){if(!state.rules)return;$("#ruleWorked").value=state.rules.worked;$("#ruleSunday").value=state.rules.sunday;$("#ruleTaken").value=state.rules.taken;$("#rulePointZero").value=state.rules.pointZero;}

  function csvServices(){const headers=["date","uo","ligne","service","police","coquille","debut","fin","debut2","fin2","duree_minutes","retard","decalage","incident","accident","lieu","note"];const q=v=>'"'+String(v??"").replace(/"/g,'""')+'"';return[headers.join(";"),...state.services.map(s=>[s.date,s.uo,s.line,s.service,s.police,s.vehicle,s.start,s.end,s.start2,s.end2,s.durationMinutes,s.delay,s.shift,s.incident,s.accident,s.location,s.note].map(q).join(";"))].join("\n");}
  function printReport(){const latest=state.months.at(-1);const w=window.open("","_blank");if(!w){toast("La fenêtre d’impression a été bloquée.");return;}const rows=state.months.map(m=>`<tr><td>${m.period}</td><td>${m.uo}</td><td>${rf(m.officialOpening)}</td><td>${signedRF(m.movementRF)}</td><td>${signedRF(m.recognizedAdjustment)}</td><td>${rf(m.theoreticalBeforeCPMA)}</td><td>${signedRF(m.cpma)}</td><td>${rf(m.officialClosing)}</td><td>${rf(m.personalCumulative)}</td><td>${signedRF(m.cumulativeGap)}</td><td>${rf(m.control)}</td></tr>`).join("");const incidents=state.incidents.map(i=>`<section><h3>${dateFR(i.date)} — ${html(i.type)}</h3><p><b>${html(i.location)}</b> · L${html(i.line||"—")} / S${html(i.service||"—")}</p><p>${html(i.description)}</p></section>`).join("");w.document.write(`<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>Dossier RF CPMA</title><style>@page{size:A4 landscape;margin:10mm}body{font:10px Arial;color:#17212b}h1{font-size:20px}h2{font-size:15px;margin-top:24px}.k{display:flex;gap:12px}.k div{border:1px solid #aaa;padding:10px;min-width:150px}.k strong{display:block;font-size:18px}table{border-collapse:collapse;width:100%;font-size:7.5px}th,td{border:1px solid #bbb;padding:4px;text-align:right}th:first-child,td:first-child,th:nth-child(2),td:nth-child(2){text-align:left}th{background:#dce8f3}section{break-inside:avoid;border-bottom:1px solid #ccc}</style></head><body><h1>Journal Machiniste PRO — Synthèse RF / CPMA</h1><p>Période exhaustive : février 2023 à mai 2026 — 40 mois reconstitués.</p><div class="k"><div>RF théorique<strong>${rf(latest.personalCumulative)}</strong></div><div>RF officiel<strong>${rf(latest.officialClosing)}</strong></div><div>Différentiel<strong>${signedRF(latest.cumulativeGap)}</strong></div></div><h2>Synthèse mensuelle</h2><table><thead><tr><th>Période</th><th>UO</th><th>Début officiel</th><th>Mvt RF</th><th>Ajust.</th><th>Théorique avant CPMA</th><th>CPMA</th><th>Bulletin</th><th>Cumul personnel</th><th>Écart</th><th>Contrôle</th></tr></thead><tbody>${rows}</tbody></table><h2>Méthodologie</h2><p>RF net = acquisition − prise. Contrôle : ouverture officielle + mouvement RF + CPMA = clôture officielle. Le transfert identifié de 12 RF vers le CET en février 2024 est isolé du différentiel.</p>${incidents?`<h2>Incidents enregistrés</h2>${incidents}`:""}<script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close();}

  function bindEvents(){
    document.addEventListener("click",async e=>{
      const r=e.target.closest("[data-route]");if(r){route(r.dataset.route);return;}const g=e.target.closest("[data-goto]");if(g){route(g.dataset.goto);return;}
      const es=e.target.closest("[data-edit-service]");if(es){editService(es.dataset.editService);return;}const ds=e.target.closest("[data-delete-service]");if(ds&&confirm("Supprimer ce service ?")){await db.delete("services",ds.dataset.deleteService);await loadState();renderServices();renderDashboard();toast("Service supprimé.");return;}
      const month=e.target.closest("[data-month]");if(month){openMonth(month.dataset.month);return;}
      const vd=e.target.closest("[data-view-document]");if(vd){openDocument(vd.dataset.viewDocument);return;}const dd=e.target.closest("[data-delete-document]");if(dd&&confirm("Supprimer ce PDF de la base locale ?")){await db.delete("documents",dd.dataset.deleteDocument);await loadState();renderDocuments();renderDashboard();toast("PDF supprimé.");return;}
      const ei=e.target.closest("[data-edit-incident]");if(ei){editIncident(ei.dataset.editIncident);return;}const di=e.target.closest("[data-delete-incident]");if(di&&confirm("Supprimer cet événement ?")){await db.delete("incidents",di.dataset.deleteIncident);await loadState();renderIncidents();toast("Événement supprimé.");}
    });
    $("#menuButton").addEventListener("click",()=>$(".sidebar").classList.toggle("open"));
    $("#serviceSplit").addEventListener("change",e=>{$("#splitFields").classList.toggle("hidden",!e.target.checked);updateDuration();});["serviceStart","serviceEnd","serviceStart2","serviceEnd2"].forEach(id=>$("#"+id).addEventListener("input",updateDuration));
    $("#serviceForm").addEventListener("submit",async e=>{e.preventDefault();const s=serviceFromForm();if(!s.date||!s.line||!s.service){toast("Date, ligne et service sont obligatoires.");return;}if((s.start&&minuteOfDay(s.start)==null)||(s.end&&minuteOfDay(s.end)==null)){toast("Horaire HHMM invalide.");return;}await db.put("services",s);await db.audit("service_saved",{id:s.id,date:s.date,line:s.line});await loadState();resetServiceForm();renderServices();renderDashboard();toast("Service enregistré.");});$("#resetServiceForm").addEventListener("click",resetServiceForm);["serviceSearch","serviceFilterDate"].forEach(id=>$("#"+id).addEventListener("input",renderServices));$("#clearServiceFilters").addEventListener("click",()=>{$("#serviceSearch").value="";$("#serviceFilterDate").value="";renderServices();});
    ["rfYearFilter","rfUoFilter"].forEach(id=>$("#"+id).addEventListener("change",renderRF));$("#recalculateRF").addEventListener("click",async()=>{await recalculateMonths({fromDays:true});await loadState();renderAll();toast("Mouvements et cumuls recalculés depuis les données quotidiennes.");});$("#saveMonthEdit").addEventListener("click",saveMonth);
    $("#xlsxInput").addEventListener("change",e=>e.target.files[0]&&handleXlsx(e.target.files[0]));$("#pdfInput").addEventListener("change",e=>e.target.files.length&&handlePdfs(e.target.files));$("#cancelImport").addEventListener("click",()=>{state.pendingImport=null;$("#importPreviewPanel").classList.add("hidden");$("#xlsxInput").value="";$("#xlsxImportStatus").textContent="Import annulé.";});$("#confirmImport").addEventListener("click",confirmImport);$("#documentStatusFilter").addEventListener("change",renderDocuments);$("#validateDocument").addEventListener("click",validateDocument);
    $("#incidentForm").addEventListener("submit",async e=>{e.preventDefault();const i=incidentFromForm();await db.put("incidents",i);await loadState();resetIncidentForm();renderIncidents();toast("Événement enregistré.");});$("#resetIncidentForm").addEventListener("click",resetIncidentForm);
    $("#dspForm").addEventListener("submit",async e=>{e.preventDefault();state.dsp={id:"main",lot:$("#dspLot").value.trim(),operator:$("#dspOperator").value.trim(),centres:$("#dspCentres").value.split(",").map(x=>x.trim()).filter(Boolean),referencePeriodStart:$("#dspStart").value,referencePeriodEnd:$("#dspEnd").value,plannedDaysPerYear:num($("#dspPlannedDays").value),executedDays:num($("#dspExecutedDays").value),note:$("#dspNote").value.trim(),updatedAt:new Date().toISOString()};await db.put("dsp",state.dsp);renderDSP();toast("Paramètres DSP enregistrés.");});
    $("#rulesForm").addEventListener("submit",async e=>{e.preventDefault();state.rules={worked:num($("#ruleWorked").value),sunday:num($("#ruleSunday").value),taken:num($("#ruleTaken").value),pointZero:num($("#rulePointZero").value)};await db.put("settings",{key:"rules",value:state.rules});await recalculateMonths();await loadState();renderAll();toast("Règles enregistrées et cumuls recalculés.");});
    $("#exportXlsx").addEventListener("click",async()=>{try{$("#exportXlsx").disabled=true;const blob=await JMPXLSX.exportWorkbook(state);downloadBlob(`Journal_Machiniste_PRO_${localToday()}.xlsx`,blob);toast("Classeur Excel généré.");}catch(e){console.error(e);toast("Échec de l’export Excel : "+e.message);}finally{$("#exportXlsx").disabled=false;}});$("#exportPdf").addEventListener("click",printReport);$("#exportCsv").addEventListener("click",()=>downloadText(`Journal_services_${localToday()}.csv`,"\ufeff"+csvServices(),"text/csv;charset=utf-8"));
    $("#exportBackup").addEventListener("click",async()=>{const data=await db.exportData($("#includePdfBackup").checked);downloadText(`Journal_Machiniste_PRO_sauvegarde_${localToday()}.json`,JSON.stringify(data,null,2),"application/json");toast("Sauvegarde générée.");});$("#restoreInput").addEventListener("change",async e=>{const f=e.target.files[0];if(!f)return;try{const p=JSON.parse(await f.text());if(!confirm("Remplacer la base locale par cette sauvegarde ?"))return;await db.restoreData(p);await loadState();populateStatic();renderAll();toast("Sauvegarde restaurée.");}catch(err){toast("Restauration impossible : "+err.message);}finally{e.target.value="";}});
    $("#resetHistorical").addEventListener("click",async()=>{if(!confirm("Réinitialiser les 40 mois à partir du référentiel intégré ? Les services et incidents seront conservés."))return;await db.replaceStore("months",JMP_SEED.monthly);await db.replaceStore("days",JMP_SEED.daily);await loadState();renderAll();toast("Référentiel historique réinitialisé.");});$("#clearDocuments").addEventListener("click",async()=>{if(!confirm("Supprimer tous les PDF stockés localement ?"))return;await db.clear("documents");await loadState();renderAll();toast("PDF locaux supprimés.");});$("#clearAllData").addEventListener("click",async()=>{if(!confirm("Effacer services, incidents, PDF, réglages et historique local ?"))return;if(!confirm("Confirmation définitive : poursuivre l’effacement ?"))return;await db.clearAll();await db.initialize(JMP_SEED);await loadState();populateStatic();renderAll();toast("Application réinitialisée.");});
    window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();state.deferredInstall=e;$("#installButton").classList.remove("hidden");});$("#installButton").addEventListener("click",async()=>{if(!state.deferredInstall)return;state.deferredInstall.prompt();await state.deferredInstall.userChoice;state.deferredInstall=null;$("#installButton").classList.add("hidden");});
  }

  init();
})();
